# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'connection'
- script: |
    sessionInfo=$(curl -u "emmamalysz_4PgZUS:BRKYBgoRtwernJha1Pjk" https://api.browserstack.com/automate/sessions/0e000cc1375fd32b51fccd8a7d4abcb5a75407f5.json | jq -r '.automation_session')
    echo "$sessionInfo";

  displayName: 'Upload app'
