# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'connection'
- script: |
    sessionInfo=$(curl -u "emmamalysz_4PgZUS:BRKYBgoRtwernJha1Pjk" -X GET "https://api-cloud.browserstack.com/app-automate/espresso/v2/builds/1d51c7955ab46c04e958d8ae6bc67f0f567ce611/sessions/6415c563c43884553eb915e7ea94e91475c0190524084317")
    echo "$output";

  displayName: 'Upload app'
